config/routes.rb
Rails.application.routes.draw do

  root 'compilations#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :compilations do
    put :favourite, on: :member
    get :favourite_data, on: :member
  end

  namespace :embed do
    resources :compilations, only: :show
  end
  

end

app/models/compilation.rb
class Compilation < ActiveRecord::Base
  belongs_to :user
  has_many :tweets, dependent: :destroy
  has_many :favourite_compilations, dependent: :destroy
  has_many :favourited_by, through: :favourite_compilations, source: :user

  validates_presence_of :user, :title

  accepts_nested_attributes_for :tweets, :reject_if => lambda { |a| a[:link].blank? }, allow_destroy: true

  def to_param
    [id, title.parameterize].join("-")
  end

end

app/models/favourite_compilation.rb
class FavouriteCompilation < ActiveRecord::Base
  belongs_to :user
  belongs_to :compilation, counter_cache: :fave_count

  validates_presence_of :user, :compilation

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :compilation
  validates_presence_of :link
  validates :link, format:{with: /https?:\/\/twitter\.com\/\w+\/status\/\d+/i, message: :format} 
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :compilations, dependent: :destroy

  has_many :favourite_compilations, dependent: :destroy
  has_many :favourites, through: :favourite_compilations, source: :compilation

  validates_presence_of :provider, :uid
  validates :provider, uniqueness: { scope: :uid }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider   = auth.provider 
      user.uid        = auth.uid
      user.name       = auth.info.name
      user.nickname   = auth.info.nickname
      user.image_url  = auth.info.image
      user.save
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/' unless current_user
  end
  
end

app/controllers/compilations_controller.rb
class CompilationsController < ApplicationController

  before_filter :authorize, except: [:index, :show, :favourite_data]

  before_filter :set_compilation, except: [:index, :new, :create]
  before_filter :can_modify_compilation?, except: [:index, :new, :create, :show, :favourite, :favourite_data]

  def index
    @compilations = Compilation.all
    if params[:sort] == "new"
      @compilations = @compilations.order('id DESC')
    else
      @compilations = @compilations.order('fave_count DESC')
    end
  end

  def new
    @compilation = Compilation.new
    @compilation.tweets.build
  end

  def create
    @compilation = current_user.compilations.new(compilation_params)
    if @compilation.save
      redirect_to(@compilation, :notice => 'Successfully created.')
    else
      render :action => "new"
    end
  end

  def show;end

  def edit;end

  def update
    if @compilation.update(compilation_params)
      redirect_to(@compilation, :notice => 'Successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @compilation.destroy
    redirect_to root_url
  end

  def favourite
    if params[:type] == "fave"
      current_user.favourites << @compilation
    else
      current_user.favourites.delete @compilation
    end
    render json: {count: @compilation.fave_count}
  end

  def favourite_data
    count = @compilation.fave_count
    fave = current_user ? current_user.favourites.find_by(id: @compilation.id).present? : false
    render json: {count: count, fave_status: fave}
  end

  private

  def set_compilation
    @compilation = Compilation.find params[:id]
  end

  def can_modify_compilation?
    unless current_user.id == @compilation.user.id
      redirect_to(@compilation, :error => 'Permission Denied.')
    end
  end

  def compilation_params
    params.require(:compilation).permit(:title, :description, tweets_attributes: [:id, :link, :title, :_destroy])
  end

end

app/controllers/embed/compilations_controller.rb
class Embed::CompilationsController < ActionController::Base
  layout false
  before_filter :set_compilation

  def show;end

  private

  def set_compilation
    @compilation = Compilation.find params[:id]
    response.headers.delete "X-Frame-Options"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to (env["omniauth.params"]["redirect_to"] || '/')
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def link_to_compile
    current_user ? new_compilation_path : twitter_auth_url(new_compilation_url)
  end

  def twitter_auth_url(url = nil)
    redirect_url = url || request.original_url
    "/auth/twitter/?redirect_to=" + CGI.escape(redirect_url)
  end

  def tweet_intent(c)
    "https://twitter.com/intent/tweet?text=#{CGI.escape(c.title)}&url=#{CGI.escape(compilation_url(c))}&via=titoree_tweets"
  end

  def fb_intent(c)
    "https://www.facebook.com/sharer/sharer.php?u=#{CGI.escape(compilation_url(c))}"
  end

end

app/views/compilations/_form.html.erb
<%= form_for(@compilation) do |f| %>
 
  <% if @compilation.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <% @compilation.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </div>
  <% end %>
 
  <div class="row mb-4 pb-2 border-bottom">
    <div class="col-md-4">
      <p class="mb-0">Compilation Details</p>
      <small class="text-muted">Tell us what your compilation is all about.</small>
    </div>
    <div class="col-md-8">
      <div class="field form-group">
        <%= f.label :title %> <span class="text-danger">*</span>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>      
    </div>
  </div>

  <div class="row mb-4 pb-2 border-bottom">
    <div class="col-sm-4">
      <p class="mb-0">Tweets Details</p>
      <small class="text-muted">Add tweets to this compilation.</small>
    </div>
    <div class="col-sm-8">
        <%= f.fields_for :tweets do |builder| %>
          <%= render 'tweet_fields', f: builder %>
        <% end %>
        
        <%= link_to_add_fields "+ Add more Tweets", f, :tweets %>
        
    </div>
  </div>

  <div class="actions float-right">
    <a class="btn btn-secondary" href="<%= @compilation.new_record? ? '/' : compilation_path(@compilation.id) %>">Cancel</a>
    <% btn_name = @compilation.new_record? ? "Create" : "Save" %>
    <%= f.submit btn_name, class:"btn btn-primary" %>
  </div>


<% end %>

app/views/compilations/_tweet_fields.html.erb
<fieldset class="py-3 border-bottom">

  <%= f.hidden_field :_destroy %>
  <a href="#" class="btn btn-outline-secondary btn-sm float-right remove_fields mb-2 rm-tweet"> Remove</a>

  <div class="form-group">
    <%= f.label :link, "Tweet URL" %> <span class="text-danger">*</span>
    <%= f.text_field :link, class: 'form-control' %> 
  </div>

  <div class="form-group">
    <%= f.label :title, "Tweet Caption"%>
    <%= f.text_field :title, class: 'form-control' %>
  </div>



</fieldset>

app/views/compilations/edit.html.erb
<div class="border-bottom mb-3">
  <div class="py-2 my-2">
    <p class="text-l my-0">Edit Compilation</p>
  </div>
</div>
<%= render "form" %>

app/views/compilations/index.html.erb
<% @compilations.each do |c| %>
<div class="media my-3 py-2">
  <img class="d-flex mr-3 rounded" src="<%= c.user.image_url %>" alt="<%= c.user.nickname %>">
  <div class="media-body">
    <div>
      <%= link_to c.title, compilation_path(c), class:'nostyle text-l' %>
    </div>
    <%= c.description %>
  </div>
</div>
<% end %>

app/views/compilations/new.html.erb
<div class="border-bottom mb-3">
  <div class="py-2 my-2">
    <p class="text-l my-0">New Compilation</p>
  </div>
</div>
<%= render "form" %>

app/views/compilations/show.html.erb
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<% content_for :head do %>
<meta property="og:url" content="<%= compilation_url(@compilation) %>" />
<meta property="og:type" content="article" />
<meta property="og:title" content="<%= @compilation.title %>" />
<meta property="og:description" content="<%= @compilation.description %>" />
<meta property="og:image" content="http://www.onlinemoneyblog.com.ng/wp-content/uploads/2015/11/2.jpg" />

<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@titoree_tweets" />
<meta name="twitter:title" content="<%= @compilation.title %>" />
<meta name="twitter:description" content="<%= @compilation.description %>" />
<meta name="twitter:image" content="http://www.onlinemoneyblog.com.ng/wp-content/uploads/2015/11/2.jpg" />

<% end %>


<div class="my-4 border-bottom">
  <h3><%= @compilation.title %></h3>
  <p><%= @compilation.description %></p>  

  <% if current_user && current_user.id == @compilation.user.id %>
  <div class="float-right my-2">
    <%= link_to 'Edit', edit_compilation_path(@compilation), class:"btn btn-outline-primary" %>
    <%= link_to "Delete", compilation_path(@compilation), method: :delete, data: { confirm: 'Are you certain you want to delete this compilation?' }, class: "btn btn-outline-danger" %>
  </div>
  <% end %>
</div>

<% @compilation.tweets.each do |t| %>
<div class="my-4">
  <p><%= t.title %></p>
  <blockquote class="twitter-tweet" data-conversation="none" data-lang="en"><a href="<%= t.link %>"></a></blockquote>
</div>
<% end %>


<div id="footer-btns" class="my-4 border-top">
  <p>
    <div id="fave">
      <% if current_user.present? %>
        <a href="" class="faveicons" id="fave">
          <i class="fa fa-heart-o" aria-hidden="true"></i>
        </a>
      <% else %>
      <a href="<%= twitter_auth_url %>" class="faveicons">
          <i class="fa fa-heart-o" aria-hidden="true"></i>
        </a>
      <% end %>
      <span class="fav-count">0</span>
    </div>

    <a href="<%= tweet_intent(@compilation) %>" class="btn btn-primary">
      <i class="fa fa-twitter" aria-hidden="true"></i>&nbsp;
      Share on Twitter
    </a>
    <a id="fbshare" href="<%= fb_intent(@compilation) %>" class="btn btn-primary">
      <i class="fa fa-facebook" aria-hidden="true"></i>&nbsp;
      Share on Facebook
    </a>
    <a id="embed" class="btn btn-secondary" href="#">Embed this to your website</a>
  </p>
  <div id="embed_code" style="display:none;">
    <p>Copy and paste the code below to embed this compilation to your website.</p>
    <div style="background-color:#F8F9FB;">
      <code id="embed">
      &lt;iframe src="<%= embed_compilation_url @compilation %>" frameborder="0" width="500px;" height="XYZpx;"&gt;&lt;/iframe&gt;
      </code>
    </div>
  </div>
</div>

app/views/embed/compilations/show.html.erb
<style>
  .my-4{
    margin-top: 4px;
    margin-bottom: 4px;
  }
  .border-bottom{
    border-bottom: 1px solid #e9ecef;
  }
</style>

<div class="my-4 border-bottom">
  <h3><%= @compilation.title %></h3>
  <p><%= @compilation.description %></p>
</div>

<% @compilation.tweets.each do |t| %>
  <div class="my-4">
    <p><%= t.title %></p>
    <blockquote class="twitter-tweet" data-conversation="none" data-lang="en"><a href="<%= t.link %>"></a></blockquote>
  </div>
<% end %>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>TweetList</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= content_for?(:head) ? yield(:head) : '' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
  <% if Rails.env == "production"  %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-65105340-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-65105340-2');
    </script>
  <% end %>

</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Titoree</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav mr-auto">
      <a class="nav-item nav-link <%= 'active' if params[:sort] != 'new'%>" href="/compilations?sort=top">Top</span></a>
      <a class="nav-item nav-link <%= 'active' if params[:sort] == 'new'%>" href="/compilations?sort=new">New</span></a>
    </div>
    <div class="navbar-nav ml-auto">
      <a class="btn btn-md btn-outline-light bg-transparent" href="<%= link_to_compile %>">Create</a>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>

<%= javascript_tag do %>
  window.compilation_id = "<%= @compilation ? @compilation.id : nil %>";
<% end %>

</html>